### ISSUE TITLE
No options in readme?

### ISSUE THREAD

**Issue by ovidijusr** [jonathantneal/postcss-env-function#1]
Is there any options list to look how can you set it?

**Comment by jonathantneal** [comment]
These are added in v2! 😄

There is an `importFrom` option which lets you import environment variables from a file.

https://github.com/jonathantneal/postcss-env-function#importfrom

It works similarly to `importFrom` options in PostCSS Custom Properties, PostCSS Custom Media, and PostCSS Color Mod Function.

- https://github.com/postcss/postcss-custom-properties#importfrom
- https://github.com/postcss/postcss-custom-media#importfrom
- https://github.com/jonathantneal/postcss-color-mod-function#importfrom
